version: '3.9'
services:
  site:
    image: node:18
    ports:
      - 3000:3000
    volumes:
      - ./:/project
    command: >
      sh -c " cd /project && npm install && npm run dev -- --host 0.0.0.0 & tail -f /dev/null "
  tests:
    image: mcr.microsoft.com/playwright:focal
    depends_on:
      - site
